In [1]:
import pandas as pd
import numpy as np

# Load data from file
df = pd.read_csv("final_df_317_1.csv")
df

,PATIENT_ID,ADMISSION_ID,AGE_AT_ICU_ADMIT,GENDER,ICU_LOS,HOSP_LOS,ICU_EXPIRE_FLAG,HOSP_EXPIRE_FLAG,30_DAYS_EXPIRE_FLAG,DELIRIUM_FLAG,...,I019_Crushing,I019_Dull,I019_Heavy,I019_Intermittent,I019_Pressure,I019_Sharp,I019_Stabbing,I019_Throbbing,I019_With Coughing,I019_With Movement
0,P00000,A39362,71.0,F,61.9,62.8,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,P00001,A25130,68.0,M,3.2,19.1,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,P00002,A19016,53.0,M,3.8,14.1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,P00004,A21002,68.0,M,2.5,2.5,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P00005,A15977,66.0,F,3.7,27.6,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47776,P48693,A55217,65.0,F,5.5,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47777,P48694,A55225,21.0,M,1.4,1.4,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47778,P48695,A55352,65.0,M,3.1,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47779,P48696,A55680,26.0,F,1.1,NaN,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47780,P48697,A32568,93.0,F,17.7,18.2,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Preprocessing Pipeline
- Extract 1000 testing samples
- Extract 50 common patients
- impute missing values
- Turn gender into binary

In [2]:
test1000 = pd.read_csv("1000Patients.csv")
testing_ids = test1000['PATIENT_ID']

In [3]:
admission_ids = test1000['ADMISSION_ID']
#admission_ids
testing_set = df[df['ADMISSION_ID'].isin(admission_ids)]
testing_set.reset_index(drop=True, inplace=True)
testing_set

,PATIENT_ID,ADMISSION_ID,AGE_AT_ICU_ADMIT,GENDER,ICU_LOS,HOSP_LOS,ICU_EXPIRE_FLAG,HOSP_EXPIRE_FLAG,30_DAYS_EXPIRE_FLAG,DELIRIUM_FLAG,...,I019_Crushing,I019_Dull,I019_Heavy,I019_Intermittent,I019_Pressure,I019_Sharp,I019_Stabbing,I019_Throbbing,I019_With Coughing,I019_With Movement
0,P02324,A47349,75.0,M,21.7,185.7,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P02325,A47759,64.0,F,2.8,3.2,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,P02388,A49358,90.0,F,7.8,10.8,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P02401,A46919,63.0,F,2.8,6.1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,P02414,A49560,71.0,F,2.1,4.8,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,P34631,A47043,71.0,M,6.0,7.6,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,P34632,A48958,29.0,F,2.5,5.6,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
987,P34633,A49002,69.0,F,6.4,55.5,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
988,P34634,A49963,74.0,M,1.0,5.9,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
989,P34635,A50556,29.0,M,4.2,4.2,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Get the admission IDs from the original DataFrame
all_admission_ids = set(test1000['ADMISSION_ID'])

# Get the admission IDs from the testing set
testing_admission_ids = set(testing_set['ADMISSION_ID'])

# Find the admission IDs that are not in the testing set
admission_ids_not_in_testing_set = all_admission_ids - testing_admission_ids

print("Admission IDs not in testing set:", admission_ids_not_in_testing_set)

Admission IDs not in testing set: {'A49728', 'A47403', 'A48970', 'A50508', 'A48091', 'A49267', 'A47182', 'A50871', 'A50212', 'A49827'}

In [5]:
#common50 = pd.read_csv("Common50.csv")
#common50['PATIENT_ID']

In [6]:
#from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

from imblearn.over_sampling import SMOTE
#SMOTENC
from imblearn.pipeline import Pipeline as ImbPipeline

In [7]:
training_set = df[~df['PATIENT_ID'].isin(testing_ids)]
training_set

,PATIENT_ID,ADMISSION_ID,AGE_AT_ICU_ADMIT,GENDER,ICU_LOS,HOSP_LOS,ICU_EXPIRE_FLAG,HOSP_EXPIRE_FLAG,30_DAYS_EXPIRE_FLAG,DELIRIUM_FLAG,...,I019_Crushing,I019_Dull,I019_Heavy,I019_Intermittent,I019_Pressure,I019_Sharp,I019_Stabbing,I019_Throbbing,I019_With Coughing,I019_With Movement
0,P00000,A39362,71.0,F,61.9,62.8,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,P00001,A25130,68.0,M,3.2,19.1,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,P00002,A19016,53.0,M,3.8,14.1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,P00004,A21002,68.0,M,2.5,2.5,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P00005,A15977,66.0,F,3.7,27.6,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47776,P48693,A55217,65.0,F,5.5,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47777,P48694,A55225,21.0,M,1.4,1.4,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47778,P48695,A55352,65.0,M,3.1,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47779,P48696,A55680,26.0,F,1.1,NaN,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47780,P48697,A32568,93.0,F,17.7,18.2,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [8]:
# Define the target column
target_column = 'HOSP_EXPIRE_FLAG' 

# Drop the target columns and patient identifiers to create X_train
X_train = training_set.drop(columns=['HOSP_EXPIRE_FLAG','PATIENT_ID', 'ADMISSION_ID', 'ICU_LOS', 'HOSP_LOS', 'ICU_EXPIRE_FLAG', 'ICU_EXPIRE_FLAG', '30_DAYS_EXPIRE_FLAG', 'DELIRIUM_FLAG'])

# Extract the target values to create y_train
y_train = training_set[target_column]

In [9]:
X_test = testing_set.drop(columns=['HOSP_EXPIRE_FLAG','PATIENT_ID', 'ADMISSION_ID', 'ICU_LOS', 'HOSP_LOS', 'ICU_EXPIRE_FLAG', 'ICU_EXPIRE_FLAG', '30_DAYS_EXPIRE_FLAG', 'DELIRIUM_FLAG'])

# Extract the target values to create y_train
y_test = testing_set[target_column]

In [10]:
X_train

,AGE_AT_ICU_ADMIT,GENDER,average_rate_I593,iqr_rate_I593,max_rate_I593,median_value_rate_I593,min_rate_I593,percentile_25_rate_I593,percentile_75_rate_I593,rate_range_I593,...,I019_Crushing,I019_Dull,I019_Heavy,I019_Intermittent,I019_Pressure,I019_Sharp,I019_Stabbing,I019_Throbbing,I019_With Coughing,I019_With Movement
0,71.0,F,238.607500,41.57250,45.01,37.5050,1.25,3.4375,45.01000,43.76,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,68.0,M,258.025000,0.93750,252.50,251.3750,250.25,251.0625,252.00000,2.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,53.0,M,0.000000,0.00000,0.00,0.0000,0.00,0.0000,0.00000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,68.0,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,66.0,F,208.231667,21.75000,100.00,1.5000,0.90,1.1250,22.87500,99.10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47776,65.0,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47777,21.0,M,145.105263,4.70000,500.00,3.5000,0.60,1.5500,6.25000,499.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47778,65.0,M,84.750000,5.00000,25.00,22.5000,20.00,20.0000,25.00000,5.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47779,26.0,F,202.830000,0.00000,10.00,10.0000,10.00,10.0000,10.00000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47780,93.0,F,383.877778,133.80125,513.58,383.4725,250.25,315.0000,448.80125,263.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [11]:
#numerical_features = tuple(range(2, 525))
numerical_features = X_train.columns[0:1].tolist() + X_train.columns[2:524].tolist()
#numerical_features

In [12]:
#categorical_feature
categorical_features = X_train.columns[524:567].tolist()
#categorical_features

In [13]:
# Create preprocessing pipeline for numeric features
numeric_transformer = ImbPipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [14]:
# Create preprocessing pipeline for categorical features
categorical_transformer = ImbPipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('scaler', StandardScaler())
])

In [16]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
# Combine preprocessing for numeric and categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first'), ['GENDER']),
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])


# Define the feature selection step using SelectFromModel
#feature_selection = SelectFromModel(logistic_regression)

# Define the SMOTE step
smote = SMOTE()

# Create the full pipeline with SMOTE
pipeline = ImbPipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', smote)
    #('feature_selection', feature_selection)
])

In [17]:
X_train.isnull().any()

AGE_AT_ICU_ADMIT      False
GENDER                False
average_rate_I593      True
iqr_rate_I593          True
max_rate_I593          True
                      ...
I019_Sharp             True
I019_Stabbing          True
I019_Throbbing         True
I019_With Coughing     True
I019_With Movement     True
Length: 566, dtype: bool

In [18]:
# Preprocess training set
X_train_preprocessed = pipeline.fit_transform(X_train)

# Preprocess testing set
X_test_preprocessed = pipeline.transform(X_test)

ValueError: Expected array-like (array or non-string sequence), got None

In [ ]:
X_train_preprocessed.shape
X_test_preprocessed.shape

In [ ]:
X_train_final = pd.DataFrame(X_train_preprocessed)
X_train_final

In [ ]:
X_train_final.isnull().any().any()

In [ ]:
# X_test_final = pd.DataFrame(X_test_preprocessed)
# #X_test_final

In [ ]:
param_dist = {
    'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],  # Regularization parameter
    'classifier__penalty': ['l1', 'l2'],  # Penalty term
    'classifier__solver': ['liblinear'],  # Solver for logistic regression
}

In [ ]:
# Define the RandomizedSearchCV with 10-fold cross-validation
random_search = RandomizedSearchCV(
    estimator= LogisticRegression(),
    param_distributions=param_dist,
    n_iter=10,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=10, shuffle=True, random_state=42),
    verbose=2,
    random_state=42,
    n_jobs=-1
)

In [ ]:
# Fit the pipeline with RandomizedSearchCV
random_search.fit(X_train, y_train)

In [ ]:
# Get the best parameters
best_params = random_search.best_params_
print("Best hyperparameters:", best_params)

# Evaluate the best model on the testing set
best_model = random_search.best_estimator_
test_auc = roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1])
print("Test AUC:", test_auc)