# Create Admissions Table

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
icu_file_path = '/home/lu.kuang/thesis/Prospective_DataCleaning/updated_cleaning/DataMerged_Prospective_0430_updated.xlsx'

In [3]:
ADMISSIONS = pd.read_excel(io = icu_file_path, sheet_name = 'PATIENT VISIT')
ADMISSIONS.columns

Index(['RECORD_ID', 'MRN', 'AGE_YEARS', 'GENDER', 'DOB', 'ICU_ADMIT',
       'ICU_DISCHARGE', 'ADMITTED_FROM', 'TRANSFER_DELAY', 'HOSP_ADMIT',
       'HOSP_DISCHARGE', 'SITE', 'ADMIT_TYPE', 'ADMIT_CLASS', 'ADMIT_APACHE2',
       'ADMIT_APACHE3', 'ADMIT_SOFA', 'ADMIT_GCS', 'ADMIT_DX', 'ICU_SURVIVAL',
       'HOSP_SURVIVAL', 'ICU_LOS', 'HOSP_LOS', 'INV_MINS', 'NIV_MINS',
       'CRRT_MINS', 'IHD_MINS', 'EPINEPHRINE_MINS', 'NOREPINEPHRINE_MINS',
       'PHENYLEPHRINE_MINS', 'DOPAMINE_MINS', 'DOBUTAMINE_MINS',
       'ISOPROTERENOL_MINS', 'DIALYSIS', 'HEARTFAIL', 'RESPINSUF',
       'IMMUNESUPR', 'CIRRHOSIS', 'DIABETES', 'AIDS', 'LEUKEMIA', 'LYMPHOMA',
       'HEPATICFAIL', 'MET_CANCER'],
      dtype='object')

In [4]:
# keeping only important fields
ADMISSIONS = ADMISSIONS[['RECORD_ID','MRN','HOSP_ADMIT','HOSP_DISCHARGE','ICU_ADMIT','ICU_DISCHARGE','SITE',
                     'ADMITTED_FROM','ADMIT_TYPE','ADMIT_CLASS','ADMIT_DX', 'ICU_SURVIVAL',
                     'HOSP_SURVIVAL', 'ICU_LOS', 'HOSP_LOS',]]
ADMISSIONS

,RECORD_ID,MRN,HOSP_ADMIT,HOSP_DISCHARGE,ICU_ADMIT,ICU_DISCHARGE,SITE,ADMITTED_FROM,ADMIT_TYPE,ADMIT_CLASS,ADMIT_DX,ICU_SURVIVAL,HOSP_SURVIVAL,ICU_LOS,HOSP_LOS
0,189844,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-01 02:14:00,2021-08-03 14:08:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Recov...,EMERG,SURGICAL,"Infection/abscess, other surgery for",A,A,2.50,20.0
1,189946,1001596889,2021-08-03 03:54:00,2021-08-11 13:51:00,2021-08-03 03:54:00,2021-08-05 20:51:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,2.71,8.0
2,190055,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-04 23:56:00,2021-08-07 18:05:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"GI Abscess/cyst-primary, surgery for (for comp...",A,A,2.76,20.0
3,190072,1036362778,2021-08-05 06:52:00,2021-08-12 17:23:00,2021-08-05 06:52:00,2021-08-12 17:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,7.38,7.0
4,190106,1002625000,2021-08-05 20:09:00,2021-08-10 18:20:00,2021-08-05 20:09:00,2021-08-07 23:29:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Embolus, pulmonary",A,A,2.14,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,209687,1042419836,2022-07-18 16:33:00,2022-07-24 11:25:00,2022-07-18 16:33:00,2022-07-21 15:35:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"Facial surgery (if related to trauma, see Trauma)",A,A,2.96,5.0
348,209746,1013229958,2022-07-19 23:23:00,2022-08-02 17:24:00,2022-07-19 23:23:00,2022-07-23 18:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, analgesic (aspirin, acetaminophen)",A,A,3.79,13.0
349,209792,1041163179,2022-07-20 22:52:00,2022-07-23 07:20:00,2022-07-20 22:52:00,2022-07-23 07:20:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,TRAUMA WITH HEAD INJURY,"Head/multiple trauma, surgery for",D,D,2.13,2.0
350,209795,1013129836,2022-07-21 00:22:00,2022-07-24 19:15:00,2022-07-21 00:22:00,2022-07-24 19:15:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,3.79,3.0
351,209883,1021916406,2022-07-22 21:03:00,2022-07-24 23:56:00,2022-07-22 21:03:00,2022-07-26 08:26:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,1.62,2.0

In [5]:
PATIENTS = pd.read_csv('PATIENTS.csv', sep=";", encoding='Latin-1', index_col="ROW_ID")
PATIENTS

,PATIENT_ID,MRN,CHARTNO,ULI,PHN_ENC,GENDER,HEIGHT,DOB,DOD,HOSP_ID,DEATH_PLACE,DEATH_CAUSE
ROW_ID,,,,,,,,,,,,
0,P00000,1000292019,1.000292e+09,103714300.0,2.282225e+11,M,175.0,1943-05-19,2022-07-10 00:00:00,423.0,5.0,C719
1,P00001,1000545531,NaN,NaN,NaN,M,180.0,1953-06-29,2022-06-16 22:22:00,NaN,NaN,NaN
2,P00002,1000552495,1.000552e+09,234773110.0,9.320552e+10,F,168.0,1949-12-06,2022-04-22 23:24:00,16.0,1.0,M329
3,P00003,1000558914,1.000559e+09,897759800.0,2.434261e+11,M,179.0,1947-06-24,2022-06-16 16:03:00,16.0,1.0,C19
4,P00004,1001072881,NaN,NaN,NaN,M,182.0,1975-10-03,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
271,P00271,1045724828,NaN,NaN,NaN,M,188.0,1971-07-06,NaN,NaN,NaN,NaN
272,P00272,1045724851,NaN,NaN,NaN,M,174.0,1955-02-24,NaN,NaN,NaN,NaN
273,P00273,1045738455,NaN,NaN,NaN,M,175.0,1946-05-20,NaN,NaN,NaN,NaN
274,P00274,1045739768,NaN,NaN,NaN,M,186.0,2000-05-26,NaN,NaN,NaN,NaN
275,P00275,1045741947,NaN,NaN,NaN,F,156.0,1949-01-01,NaN,NaN,NaN,NaN

In [6]:
ADMISSIONS = ADMISSIONS.merge(right = PATIENTS[['MRN','PATIENT_ID','DOD']], on = ['MRN'])
# Convert relevant columns to datetime
datetime_cols = ['HOSP_ADMIT', 'HOSP_DISCHARGE', 'ICU_ADMIT', 'ICU_DISCHARGE']

for col in datetime_cols:
    ADMISSIONS[col] = pd.to_datetime(ADMISSIONS[col], errors='coerce')
ADMISSIONS

,RECORD_ID,MRN,HOSP_ADMIT,HOSP_DISCHARGE,ICU_ADMIT,ICU_DISCHARGE,SITE,ADMITTED_FROM,ADMIT_TYPE,ADMIT_CLASS,ADMIT_DX,ICU_SURVIVAL,HOSP_SURVIVAL,ICU_LOS,HOSP_LOS,PATIENT_ID,DOD
0,189844,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-01 02:14:00,2021-08-03 14:08:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Recov...,EMERG,SURGICAL,"Infection/abscess, other surgery for",A,A,2.50,20.0,P00033,NaN
1,189946,1001596889,2021-08-03 03:54:00,2021-08-11 13:51:00,2021-08-03 03:54:00,2021-08-05 20:51:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,2.71,8.0,P00005,NaN
2,190055,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-04 23:56:00,2021-08-07 18:05:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"GI Abscess/cyst-primary, surgery for (for comp...",A,A,2.76,20.0,P00033,NaN
3,190072,1036362778,2021-08-05 06:52:00,2021-08-12 17:23:00,2021-08-05 06:52:00,2021-08-12 17:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,7.38,7.0,P00175,2021-08-12 17:23:00
4,190106,1002625000,2021-08-05 20:09:00,2021-08-10 18:20:00,2021-08-05 20:09:00,2021-08-07 23:29:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Embolus, pulmonary",A,A,2.14,4.0,P00010,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,209687,1042419836,2022-07-18 16:33:00,2022-07-24 11:25:00,2022-07-18 16:33:00,2022-07-21 15:35:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"Facial surgery (if related to trauma, see Trauma)",A,A,2.96,5.0,P00190,NaN
348,209746,1013229958,2022-07-19 23:23:00,2022-08-02 17:24:00,2022-07-19 23:23:00,2022-07-23 18:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, analgesic (aspirin, acetaminophen)",A,A,3.79,13.0,P00076,NaN
349,209792,1041163179,2022-07-20 22:52:00,2022-07-23 07:20:00,2022-07-20 22:52:00,2022-07-23 07:20:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,TRAUMA WITH HEAD INJURY,"Head/multiple trauma, surgery for",D,D,2.13,2.0,P00184,2022-07-23 07:20:00
350,209795,1013129836,2022-07-21 00:22:00,2022-07-24 19:15:00,2022-07-21 00:22:00,2022-07-24 19:15:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,3.79,3.0,P00075,NaN
351,209883,1021916406,2022-07-22 21:03:00,2022-07-24 23:56:00,2022-07-22 21:03:00,2022-07-26 08:26:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,1.62,2.0,P00118,2022-07-24 23:56:00

In [8]:
# adjusting names of fields
ADMISSIONS.rename(columns={'HOSP_ADMIT':'HOSP_ADMIT_DATETIME',
                           'HOSP_DISCHARGE':'HOSP_DISCH_DATETIME',
                           'ICU_ADMIT':'ICU_ADMIT_DATETIME',
                           'ICU_DISCHARGE':'ICU_DISCH_DATETIME',
                           'SITE':'ADMISSION_SITE',
                           'UNIT_ADMITTED_FROM':'ADMITTED_FROM',
                           'ADMIT_TYPE':'ADMISSION_TYPE',
                           'ADMIT_CLASS':'ADMISSION_CLASS',
                           'ADMIT_DX':'ADMISSION_DIAGNOSIS',
}, inplace = True)
ADMISSIONS

,RECORD_ID,MRN,HOSP_ADMIT_DATETIME,HOSP_DISCH_DATETIME,ICU_ADMIT_DATETIME,ICU_DISCH_DATETIME,ADMISSION_SITE,ADMITTED_FROM,ADMISSION_TYPE,ADMISSION_CLASS,ADMISSION_DIAGNOSIS,ICU_SURVIVAL,HOSP_SURVIVAL,ICU_LOS,HOSP_LOS,PATIENT_ID,DOD
0,189844,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-01 02:14:00,2021-08-03 14:08:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Recov...,EMERG,SURGICAL,"Infection/abscess, other surgery for",A,A,2.50,20.0,P00033,NaN
1,189946,1001596889,2021-08-03 03:54:00,2021-08-11 13:51:00,2021-08-03 03:54:00,2021-08-05 20:51:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,2.71,8.0,P00005,NaN
2,190055,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-04 23:56:00,2021-08-07 18:05:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"GI Abscess/cyst-primary, surgery for (for comp...",A,A,2.76,20.0,P00033,NaN
3,190072,1036362778,2021-08-05 06:52:00,2021-08-12 17:23:00,2021-08-05 06:52:00,2021-08-12 17:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,7.38,7.0,P00175,2021-08-12 17:23:00
4,190106,1002625000,2021-08-05 20:09:00,2021-08-10 18:20:00,2021-08-05 20:09:00,2021-08-07 23:29:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Embolus, pulmonary",A,A,2.14,4.0,P00010,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,209687,1042419836,2022-07-18 16:33:00,2022-07-24 11:25:00,2022-07-18 16:33:00,2022-07-21 15:35:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"Facial surgery (if related to trauma, see Trauma)",A,A,2.96,5.0,P00190,NaN
348,209746,1013229958,2022-07-19 23:23:00,2022-08-02 17:24:00,2022-07-19 23:23:00,2022-07-23 18:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, analgesic (aspirin, acetaminophen)",A,A,3.79,13.0,P00076,NaN
349,209792,1041163179,2022-07-20 22:52:00,2022-07-23 07:20:00,2022-07-20 22:52:00,2022-07-23 07:20:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,TRAUMA WITH HEAD INJURY,"Head/multiple trauma, surgery for",D,D,2.13,2.0,P00184,2022-07-23 07:20:00
350,209795,1013129836,2022-07-21 00:22:00,2022-07-24 19:15:00,2022-07-21 00:22:00,2022-07-24 19:15:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,3.79,3.0,P00075,NaN
351,209883,1021916406,2022-07-22 21:03:00,2022-07-24 23:56:00,2022-07-22 21:03:00,2022-07-26 08:26:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,1.62,2.0,P00118,2022-07-24 23:56:00

In [9]:
# renaming index to ROW_ID
ADMISSIONS.index.set_names(['ROW_ID'], inplace = True)

In [10]:
# adjusting RECORD_ID to int
ADMISSIONS['RECORD_ID'] = ADMISSIONS['RECORD_ID'].apply(lambda x: int(x))

In [11]:
# creating ADMISSION_ID
ADMISSIONS['ADMISSION_ID'] = range(0,len(ADMISSIONS))
ADMISSIONS['ADMISSION_ID'] = ADMISSIONS['ADMISSION_ID'].apply(lambda x: 'PA'+str(x).rjust(5, '0'))

In [12]:
# create HOSP_READMIT
patient_ids = sorted(list(set(ADMISSIONS['PATIENT_ID'])))
for patient_id in patient_ids:
    temp = ADMISSIONS[ADMISSIONS['PATIENT_ID'] == patient_id].sort_values(by = ['HOSP_ADMIT_DATETIME'], ascending = True).reset_index()
    for x in range(len(temp)):
        index = temp.loc[x,'ROW_ID']
        if x == 0:
            temp.loc[x,'HOSP_READMIT'] = 0
        else:
            if temp.loc[x,'HOSP_ADMIT_DATETIME'] == temp.loc[x-1,'HOSP_ADMIT_DATETIME']:
                temp.loc[x,'HOSP_READMIT'] = temp.loc[x-1,'HOSP_READMIT']
            else:
                temp.loc[x,'HOSP_READMIT'] = temp.loc[x-1,'HOSP_READMIT'] + 1
        
        ADMISSIONS.loc[index,'HOSP_READMIT'] = temp.loc[x,'HOSP_READMIT']

In [13]:
# create RECUR_ICU_ADMIT
patient_ids = sorted(list(set(ADMISSIONS['PATIENT_ID'])))
for patient_id in patient_ids:
    admissions = len(set(ADMISSIONS[ADMISSIONS['PATIENT_ID'] == patient_id]['HOSP_READMIT']))    
    for admission in range(admissions):
        temp = ADMISSIONS[(ADMISSIONS['PATIENT_ID'] == patient_id) & 
                          (ADMISSIONS['HOSP_READMIT'] == admission)].sort_values(by = ['ICU_ADMIT_DATETIME'], ascending = True).reset_index()
        for x in range(len(temp)):
            index = temp.loc[x,'ROW_ID']
            if x == 0:
                temp.loc[x,'ICU_READMIT'] = 0
            else:
                if temp.loc[x,'ICU_ADMIT_DATETIME'] == temp.loc[x-1,'ICU_ADMIT_DATETIME']:
                    temp.loc[x,'ICU_READMIT'] = temp.loc[x-1,'ICU_READMIT']
                else:
                    temp.loc[x,'ICU_READMIT'] = temp.loc[x-1,'ICU_READMIT'] + 1

            ADMISSIONS.loc[index,'ICU_READMIT'] = temp.loc[x,'ICU_READMIT']

In [14]:
ADMISSIONS

,RECORD_ID,MRN,HOSP_ADMIT_DATETIME,HOSP_DISCH_DATETIME,ICU_ADMIT_DATETIME,ICU_DISCH_DATETIME,ADMISSION_SITE,ADMITTED_FROM,ADMISSION_TYPE,ADMISSION_CLASS,ADMISSION_DIAGNOSIS,ICU_SURVIVAL,HOSP_SURVIVAL,ICU_LOS,HOSP_LOS,PATIENT_ID,DOD,ADMISSION_ID,HOSP_READMIT,ICU_READMIT
ROW_ID,,,,,,,,,,,,,,,,,,,,
0,189844,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-01 02:14:00,2021-08-03 14:08:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Recov...,EMERG,SURGICAL,"Infection/abscess, other surgery for",A,A,2.50,20.0,P00033,NaN,PA00000,0.0,0.0
1,189946,1001596889,2021-08-03 03:54:00,2021-08-11 13:51:00,2021-08-03 03:54:00,2021-08-05 20:51:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,2.71,8.0,P00005,NaN,PA00001,0.0,0.0
2,190055,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-04 23:56:00,2021-08-07 18:05:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"GI Abscess/cyst-primary, surgery for (for comp...",A,A,2.76,20.0,P00033,NaN,PA00002,0.0,1.0
3,190072,1036362778,2021-08-05 06:52:00,2021-08-12 17:23:00,2021-08-05 06:52:00,2021-08-12 17:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,7.38,7.0,P00175,2021-08-12 17:23:00,PA00003,0.0,0.0
4,190106,1002625000,2021-08-05 20:09:00,2021-08-10 18:20:00,2021-08-05 20:09:00,2021-08-07 23:29:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Embolus, pulmonary",A,A,2.14,4.0,P00010,NaN,PA00004,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,209687,1042419836,2022-07-18 16:33:00,2022-07-24 11:25:00,2022-07-18 16:33:00,2022-07-21 15:35:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,"Facial surgery (if related to trauma, see Trauma)",A,A,2.96,5.0,P00190,NaN,PA00347,0.0,0.0
348,209746,1013229958,2022-07-19 23:23:00,2022-08-02 17:24:00,2022-07-19 23:23:00,2022-07-23 18:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, analgesic (aspirin, acetaminophen)",A,A,3.79,13.0,P00076,NaN,PA00348,1.0,0.0
349,209792,1041163179,2022-07-20 22:52:00,2022-07-23 07:20:00,2022-07-20 22:52:00,2022-07-23 07:20:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,TRAUMA WITH HEAD INJURY,"Head/multiple trauma, surgery for",D,D,2.13,2.0,P00184,2022-07-23 07:20:00,PA00349,0.0,0.0
350,209795,1013129836,2022-07-21 00:22:00,2022-07-24 19:15:00,2022-07-21 00:22:00,2022-07-24 19:15:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,"Overdose, street drugs (opiates, cocaine, amph...",A,A,3.79,3.0,P00075,NaN,PA00350,0.0,0.0
351,209883,1021916406,2022-07-22 21:03:00,2022-07-24 23:56:00,2022-07-22 21:03:00,2022-07-26 08:26:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,Cardiac arrest (with or without respiratory ar...,D,D,1.62,2.0,P00118,2022-07-24 23:56:00,PA00351,1.0,0.0

In [15]:
# Map survival status to binary mortality indicators
survival_map = {'A': 0, 'D': 1}

ADMISSIONS['ICU_MORTALITY'] = ADMISSIONS['ICU_SURVIVAL'].map(survival_map)
ADMISSIONS['HOSP_MORTALITY'] = ADMISSIONS['HOSP_SURVIVAL'].map(survival_map)
ADMISSIONS

,RECORD_ID,MRN,HOSP_ADMIT_DATETIME,HOSP_DISCH_DATETIME,ICU_ADMIT_DATETIME,ICU_DISCH_DATETIME,ADMISSION_SITE,ADMITTED_FROM,ADMISSION_TYPE,ADMISSION_CLASS,...,HOSP_SURVIVAL,ICU_LOS,HOSP_LOS,PATIENT_ID,DOD,ADMISSION_ID,HOSP_READMIT,ICU_READMIT,ICU_MORTALITY,HOSP_MORTALITY
ROW_ID,,,,,,,,,,,,,,,,,,,,,
0,189844,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-01 02:14:00,2021-08-03 14:08:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Recov...,EMERG,SURGICAL,...,A,2.50,20.0,P00033,NaN,PA00000,0.0,0.0,0,0.0
1,189946,1001596889,2021-08-03 03:54:00,2021-08-11 13:51:00,2021-08-03 03:54:00,2021-08-05 20:51:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,A,2.71,8.0,P00005,NaN,PA00001,0.0,0.0,0,0.0
2,190055,1005018831,2021-08-01 02:14:00,2021-08-21 11:37:00,2021-08-04 23:56:00,2021-08-07 18:05:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,...,A,2.76,20.0,P00033,NaN,PA00002,0.0,1.0,0,0.0
3,190072,1036362778,2021-08-05 06:52:00,2021-08-12 17:23:00,2021-08-05 06:52:00,2021-08-12 17:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,D,7.38,7.0,P00175,2021-08-12 17:23:00,PA00003,0.0,0.0,1,1.0
4,190106,1002625000,2021-08-05 20:09:00,2021-08-10 18:20:00,2021-08-05 20:09:00,2021-08-07 23:29:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,A,2.14,4.0,P00010,NaN,PA00004,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,209687,1042419836,2022-07-18 16:33:00,2022-07-24 11:25:00,2022-07-18 16:33:00,2022-07-21 15:35:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,SURGICAL,...,A,2.96,5.0,P00190,NaN,PA00347,0.0,0.0,0,0.0
348,209746,1013229958,2022-07-19 23:23:00,2022-08-02 17:24:00,2022-07-19 23:23:00,2022-07-23 18:23:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,A,3.79,13.0,P00076,NaN,PA00348,1.0,0.0,0,0.0
349,209792,1041163179,2022-07-20 22:52:00,2022-07-23 07:20:00,2022-07-20 22:52:00,2022-07-23 07:20:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Opera...,EMERG,TRAUMA WITH HEAD INJURY,...,D,2.13,2.0,P00184,2022-07-23 07:20:00,PA00349,0.0,0.0,1,1.0
350,209795,1013129836,2022-07-21 00:22:00,2022-07-24 19:15:00,2022-07-21 00:22:00,2022-07-24 19:15:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,A,3.79,3.0,P00075,NaN,PA00350,0.0,0.0,0,0.0
351,209883,1021916406,2022-07-22 21:03:00,2022-07-24 23:56:00,2022-07-22 21:03:00,2022-07-26 08:26:00,FMC ICU,Foothills Medical Centre (Calgary) FMC - Emerg...,NO_OP,MEDICAL,...,D,1.62,2.0,P00118,2022-07-24 23:56:00,PA00351,1.0,0.0,1,1.0

In [16]:
ADMISSIONS.to_csv('ADMISSIONS.csv', sep = ";", encoding = 'Latin-1')