In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://lu.kuang:EFTd66Qa3QhnMeA7\
@10.44.113.30/ABeICU')

# Path to the CSV file
csv_file = '/home/lu.kuang/thesis/GithubFolder/jupyterlab/DataCleaningScripts/ProspectiveCleaning/selected_features.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(csv_file)

# Extract the item prefix before the first "_" or "\" and create a new column
df['Items'] = df['Selected Features'].str.extract(r'^([^_\\]+)')

# Drop duplicate rows (if needed) and get unique item values
items = df['Items'].dropna().drop_duplicates().reset_index(drop=True)

# Display the cleaned list of items
items = pd.DataFrame(items)

In [2]:
items

     Items
0   GENDER
1     I000
2     I002
3     I009
4     I011
5     I012
6     I035
7     I037
8     I039
9     I056
10    I059
11    I060
12    I065
13    I076
14    I078
15    I010
16    I013
17    I022
18    I029
19    I033
20    I034
21    I036
22    I054
23    I055
24    I058
25    I061
26    I066
27    I067
28    I077
29    I095
30    I101
31    I103
32    I105
33    I114
34    I115
35    I003
36    I093
37    I116
38    I117
39    I001
40    I113
41    I112
42    I008
43    I099
44    I107
45    I110
46    I015
47    I023
48    I097
49    I593
50    I079
51    I108
52    I007
53    I014
54    I069
55    I111
56    I109

In [3]:
# Connect to the database
items_df = pd.read_sql_query('SELECT * FROM public."ITEMS"',con=engine)
items_df

,ROW_ID,ITEM_ID,LABEL,ABBREVIATION,CATEGORY,PARAM_TYPE,UOM
0,0.0,I000,Eye Opening,Eye Opening,GCS,NUM,None
1,1.0,I001,Verbal Response,Verbal Response,GCS,NUM,None
2,2.0,I002,Glasgow Coma Scale,GCS,GCS,NUM,None
3,3.0,I003,Motor Response,Motor Response,GCS,NUM,None
4,4.0,I004,Verbal Response - Unable to Assess,Verbal Response - Unable to Assess,GCS,CHAR,None
...,...,...,...,...,...,...,...
766,766.0,I766,Comment NIV,Comment NIV,Comments - Mechanical Ventilation,CHAR,None
767,767.0,I767,Comment HFOV,Comment HFOV,Comments - Mechanical Ventilation,CHAR,None
768,768.0,I768,Comment V2,Comment V2,Comments - Mechanical Ventilation,CHAR,None
769,769.0,I769,Out of Range Reason Comment V2,Out of Range Reason Comment V2,Comments - Mechanical Ventilation,CHAR,None
770,770.0,I770,Comment Pain Scale,Comment Pain Scale,Comments - Mechanical Ventilation,CHAR,None

In [4]:
df = items.merge(items_df, left_on='Items', right_on="ITEM_ID")
df

,Items,ROW_ID,ITEM_ID,LABEL,ABBREVIATION,CATEGORY,PARAM_TYPE,UOM
0,I000,0.0,I000,Eye Opening,Eye Opening,GCS,NUM,None
1,I002,2.0,I002,Glasgow Coma Scale,GCS,GCS,NUM,None
2,I009,9.0,I009,Psychomotor Agitation or Retardation,Psychomotor Agitation or Retardation,ICDSC,BIN,None
3,I011,11.0,I011,Altered Level of Consciousness,Altered Level of Consciousness,ICDSC,BIN,None
4,I012,12.0,I012,"Hallucination, Delusion or Psychosis","Hallucination, Delusion or Psychosis",ICDSC,BIN,None
5,I035,35.0,I035,Non-Invasive Blood Pressure - Systolic,NIBP Systolic,Vitals,NUM,mmHg
6,I037,37.0,I037,Non-Invasive Blood Pressure - Mean,NIBP Mean,Vitals,NUM,mmHg
7,I039,39.0,I039,Resp Rate Bedside Monitor,Resp Rate Bedside Monitor,Vitals,NUM,breaths/min
8,I056,56.0,I056,Creatinine Blood,Creatinine Blood,Labs,NUM,umol/L
9,I059,59.0,I059,Sodium Blood,Sodium Blood,Labs,NUM,mmol/L
10,I060,60.0,I060,Sodium Blood Gas,Sodium Blood Gas,Labs,NUM,mmol/L
11,I065,65.0,I065,Potential of Hydrogen - Arterial,PH Arterial,Labs,NUM,None
12,I076,76.0,I076,Hematocrit,Hematocrit,Labs,NUM,%
13,I078,78.0,I078,Red Blood Cells,RBC,Labs,NUM,E+12 units/L
14,I010,10.0,I010,Fluctuations,Fluctuations,ICDSC,BIN,None
15,I013,13.0,I013,Sleep Wake Cycle Disturbance,Sleep Wake Cycle Disturbance,ICDSC,BIN,None
16,I022,22.0,I022,Richmond Agitation Sedation Scale,RASS,RASS,NUM,None
17,I029,29.0,I029,Heart Rate,Heart Rate,Vitals,NUM,bpm
18,I033,33.0,I033,Oxygen Saturation,SpO2,Vitals,NUM,%
19,I034,34.0,I034,Oxygen Saturation - Site 1,SpO2 Site 1,Vitals,NUM,%
20,I036,36.0,I036,Non-Invasive Blood Pressure - Diastolic,NIBP Diastolic,Vitals,NUM,mmHg
21,I054,54.0,I054,Urea Blood,Urea Blood,Labs,NUM,mmol/L
22,I055,55.0,I055,Carbon Dioxide Content Blood,CO2 Content Blood,Labs,NUM,mmol/L
23,I058,58.0,I058,Potassium Blood,Potassium Blood,Labs,NUM,mmol/L
24,I061,61.0,I061,Partial Pressure of Carbon Dioxide - Arterial,PCO2 Arterial,Labs,NUM,mmHg
25,I066,66.0,I066,Partial Pressure of Oxygen - Arterial,PO2 Arterial,Labs,NUM,mmHg
26,I067,67.0,I067,Total Hemoglobin Blood Gas,Total Hemoglobin Blood Gas,Labs,NUM,g/L
27,I077,77.0,I077,Hemoglobin,Hemoglobin,Labs,NUM,g/L
28,I095,95.0,I095,Coagulatory (admission),Coagulatory (admission),SOFA,NUM,None
29,I101,101.0,I101,Neurologic (admission),Neurologic (admission),SOFA,NUM,None
30,I103,103.0,I103,Renal (admission),Renal (admission),SOFA,NUM,None
31,I105,105.0,I105,Sequential Organ Failure Assessment (admission),SOFA (admission),SOFA,NUM,None
32,I114,114.0,I114,Age Point,AP,Apache III (IV),NUM,None
33,I115,115.0,I115,Chronic Health Point,CHP,Apache III (IV),NUM,None
34,I003,3.0,I003,Motor Response,Motor Response,GCS,NUM,None
35,I093,93.0,I093,Respiratory (admission),Respiratory (admission),SOFA,NUM,None
36,I116,116.0,I116,Apache III (IV) Score,Apache III (IV) Score,Apache III (IV),NUM,None
37,I117,117.0,I117,Apache III (IV) Compliance,Apache III (IV) Compliance,Apache III (IV),NUM,None
38,I001,1.0,I001,Verbal Response,Verbal Response,GCS,NUM,None
39,I113,113.0,I113,Acute Physiological Score,APS,Apache III (IV),NUM,None
40,I112,112.0,I112,Apache II Compliance,Apache II Compliance,Apache II,NUM,None
41,I008,8.0,I008,Inattention,Inattention,ICDSC,BIN,None
42,I099,99.0,I099,Cardiovascular (admission),Cardiovascular (admission),SOFA,NUM,None
43,I107,107.0,I107,Age Point,AP,Apache II,NUM,None
44,I110,110.0,I110,Apache II Score,Apache II Score,Apache II,NUM,None
45,I015,15.0,I015,Inappropriate Mood or Speech,Inappropriate Mood or Speech,ICDSC,BIN,None
46,I023,23.0,I023,Urine Indwelling Catheter,Urine Indwelling Catheter,Urine Volumes,NUM,mL
47,I097,97.0,I097,Liver (admission),Liver (admission),SOFA,NUM,None
48,I593,593.0,I593,0.9% NaCl,0.9% NaCl,Prescriptions,NUM,mL
49,I079,79.0,I079,White Blood Cells,WBC,Labs,NUM,E+9 units/L
50,I108,108.0,I108,Chronic Health Point,CHP,Apache II,NUM,None
51,I007,7.0,I007,Intensive Care Delirium Screening Checklist,ICDSC,ICDSC,NUM,None
52,I014,14.0,I014,Disorientation,Disorientation,ICDSC,BIN,None
53,I069,69.0,I069,Potassium Blood Gas,Potassium Blood Gas,Labs,NUM,mmol/L
54,I111,111.0,I111,Mortality Prediction Model,MPM,Apache II,NUM,None
55,I109,109.0,I109,Acute Physiological Score,APS,Apache II,NUM,None

In [5]:
df.to_csv("items_used_in_training.csv", index=False)